FROM mcr.microsoft.com/windows/servercore:ltsc2019

WORKDIR /actions-runner

COPY InstallAgent.ps1 InstallAgent.ps1

RUN ["powershell", "InstallAgent.ps1"]

COPY ConfigureAndRun.ps1 ConfigureAndRun.ps1

ENTRYPOINT ["powershell"]
CMD ["ConfigureAndRun.ps1"]

