FROM mcr.microsoft.com/windows/servercore:ltsc2019

WORKDIR /actions-runner

COPY InstallAgent.ps1 InstallAgent.ps1

RUN powershell .\InstallAgent.ps1 windows

COPY ConfigureAndRun.ps1 ConfigureAndRun.ps1

CMD powershell .\ConfigureAndRun.ps1 windows

