FROM mcr.microsoft.com/powershell

RUN useradd -m actions && \
  apt-get update && \
  apt-get install python curl ruby -y && \
  apt-get clean

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

WORKDIR /home/actions/actions-runner

COPY InstallAgent.ps1 InstallAgent.ps1

RUN ["pwsh", "InstallAgent.ps1", "linux"]

USER actions

COPY ConfigureAndRun.ps1 ConfigureAndRun.ps1

ENTRYPOINT ["pwsh"]

CMD ["ConfigureAndRun.ps1", "linux"]
